# -*- coding: utf-8 -*-
"""dateTime.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rwrEFDYZgM9cJsqkDyw4ANHcbG0ruDaJ
"""

#Get Current Date and Time
import datetime

datetime_object = datetime.datetime.now()
#now() method to create a datetime object containing the current local date and time.
print(datetime_object)

#Get Current Date
import datetime

date_object = datetime.date.today()
print(date_object)

#What's inside datetime?
#dir() function to get a list containing all attributes of a module.
import datetime

print(dir(datetime))

#Date object to represent a date
import datetime

d = datetime.date(2019, 4, 13)
print(d)

from datetime import date

a = date(2019, 4, 13)
print(a)

#Get current date

from datetime import date

today = date.today()

print("Current date =", today)

#Get date from a timestamp
# A Unix timestamp is the number of seconds between a particular date and January 1, 1970 at UTC. 
from datetime import date

timestamp = date.fromtimestamp(1826244364)
print("Date =", timestamp)

#Print today's year, month and day
from datetime import date

# date object of today's date
today = date.today() 

print("Current year:", today.year)
print("Current month:", today.month)
print("Current day:", today.day)

#A time object instantiated from the time class represents the local time.
#Time object to represent time
from datetime import time

# time(hour = 0, minute = 0, second = 0)
a = time()
print("a =", a)

# time(hour, minute and second)
b = time(11, 34, 56)
print("b =", b)

# time(hour, minute and second)
c = time(hour = 11, minute = 34, second = 56)
print("c =", c)

# time(hour, minute, second, microsecond)
d = time(11, 34, 56, 234566)
print("d =", d)

import datetime 
  
# date and time in yyyy/mm/dd hh:mm:ss format 
d1 = datetime.datetime(2020, 5, 13, 22, 50, 55) 
d2 = datetime.datetime(2020, 7, 13, 22, 50, 55)
d3 = datetime.datetime(2020, 6, 13, 22, 50, 55)

print(d1 > d2)
print(d2 > d3)


#QUESTION - Check if Two DateTime objects are Equal

#Compare only Dates of DateTime Objects
import datetime 
  
# date and time in yyyy/mm/dd hh:mm:ss format 
d1 = datetime.datetime(2020, 5, 13, 22, 50, 55) 
d2 = datetime.datetime(2020, 5, 13, 7, 50, 55)
d3 = datetime.datetime(2020, 6, 13, 22, 50, 55)

print(d1.date() == d2.date()) #True
print(d1.date() == d3.date()) #False
print(d1.date() < d2.date()) #False
print(d1.date() < d3.date()) #True
print(d1.date() > d2.date()) #False
print(d1.date() > d3.date()) #False

#Compare only Times of DateTime Objects
import datetime 
  
# date and time in yyyy/mm/dd hh:mm:ss format 
d1 = datetime.datetime(2020, 5, 13, 22, 50, 55) 
d2 = datetime.datetime(2020, 5, 13, 7, 50, 55)
d3 = datetime.datetime(2020, 6, 13, 22, 50, 55)

print(d1.time() == d2.time()) #True
print(d1.time() == d3.time()) #False
print(d1.time() < d2.time()) #False
print(d1.time() < d3.time()) #True
print(d1.time() > d2.time()) #False
print(d1.time() > d3.time()) #False

#python program to disply calendar for given month and Time
from calendar import *
yy = int(input("Enter year:"))
mm = int(input("enter month:"))

str = month(yy,mm)
print(str)

#python program to disply calender for entire year

from calendar import *
year =int(input('enter year:'))
print(calendar(year,2,1,8,4))

#(year,w=2(width between two clm),l=1(represent blankline),c=8(clm wise space),m=3(no of month disply in row))

#sorting date
from datetime import *

group=[]

#add today's date to the list
group.append(date.today())

#crete some more date and add to the list
d = date(2015,6,29)
group.append(d)

d = date(2015,7,28)
group.append(d)

#sort the list
group.sort()

for d in group:
  print(d)