# -*- coding: utf-8 -*-
"""function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rdmLCbzYu81o7wjAzNvLibhrHj0J0qmq
"""

def greet():
  print("Hello")

# A simple Python function
def fun():
  print("Welcome")

#code to call a function
fun()

#This function expects 2 arguments, and gets 2 arguments:
def my_function(fname, lname):
  print(fname + " " + lname)

my_function("A", "J")

#This function expects 2 arguments, but gets only 1
def my_function(fname, lname):
  print(fname + " " + lname)

my_function("A")

#If you do not know how many arguments that will be passed into your function, add a * before the parameter name in the function definition.
def my_function(*STU):
  print("The student list: " + STU[1])

my_function("a", "b", "c")

#Passing a List as an Argument
def my_function(food):
  for x in food:
    print(x)

fruits = ["apple", "banana", "cherry"]

my_function(fruits)

#Return Values
def my_function(x):
  return 5 * x

print(my_function(3))
print(my_function(5))
print(my_function(9))

#function definitions cannot be empty, but if you for some reason have a function definition with no content, put in the pass statement to avoid getting an error.
def myfunction():
  pass

x = lambda a : a + 10
print(x(5))